server:
  port: 8002
spring:
  application:
    name: iedraw-parent
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iedraw?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root